config/routes.rb
Rails.application.routes.draw do

  get 'toppages', to: 'toppages#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  post 'guest', to: 'guest_sessions#create'

  resources :users, only: [:create]
  get 'signup', to: 'users#new'
  
  resources :travels, only: [:index, :new, :create, :destroy]
  root to: 'toppages#index'
  
  resources :budget_items, only: [:destroy, :update, :edit]
  get 'travels/:id/budget_items', to: 'budget_items#index',as: 'budget_items'
  get 'travels/:id/budget_items/new', to: 'budget_items#new',as: 'new_budget_item'
  post 'travels/:id/budget_items', to: 'budget_items#create'
  
  resources :paid_items, only: [:destroy, :update, :edit]
  get 'travels/:id/paid_items', to: 'paid_items#index',as: 'paid_items'
  get 'travels/:id/paid_items/new', to: 'paid_items#new',as: 'new_paid_item'
  post 'travels/:id/paid_items', to: 'paid_items#create'
  
end

app/models/travel.rb
class Travel < ApplicationRecord
  belongs_to :user
  has_many :budget_items, dependent: :destroy
  has_many :paid_items, dependent: :destroy
  mount_uploader :picture, PictureUploader
  validates :name, presence: true, length: { maximum: 20 }
  validate  :picture_size
  
  private
  
  def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]

  def index
    @travels = current_user.travels.order(id: :desc).page(params[:page]).per(4)
  end
  
  def new
    @travel = Travel.new
  end
  
  def create
    @travel = current_user.travels.build(travel_params)

    if @travel.save
      flash[:success] = '旅行を追加しました。'
      redirect_to travels_path
    else
      flash.now[:danger] = '旅行の追加に失敗しました。'
      render :new
    end
  end

  def destroy
    @travel.destroy
    flash[:success] = '旅行を削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  private

  def travel_params
    params.require(:travel).permit(:name, :picture)
  end
  
  def correct_user
    @travel = current_user.travels.find_by(id: params[:id])
    unless @travel
      redirect_to travels_path
    end
  end
end

app/views/travels/index.html.erb
<div class= 'text-center'>
  <h1 id= 'tratitle'><%= current_user.name %>さんの旅行一覧</h1>
</div>

<div class= 'text-right'>
  <%= link_to '旅行追加',  new_travel_path %>
</div>

<% @travels.each do |travel| %>

<div class="card">
    <div class="card-header text-center">
        <%= travel.name %>
    </div>
    <div class="card-body text-center">
  <%= image_tag 'ryohi1.jpg', size: '400x200' %>
　<%= link_to '予算',  budget_items_path(travel) %>(<%= travel.budget_items.all.sum(:cost) %>円)
  <%= link_to '実績',  paid_items_path(travel) %>(<%= travel.paid_items.all.sum(:cost) %>円)
  <%= link_to '旅行削除', travel, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>
    </div>
</div>
<% end %>
<%= paginate @travels %>

app/views/travels/new.html.erb
<div class="text-center">
  <h2>旅行追加画面</h2>
</div>


<%= form_with(model: @travel, local: true) do |f| %>

<%= render 'layouts/error_messages', model: f.object %>

  <div class="form-group">
    <%= f.label :name, '旅行名' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <%= f.submit '追加', class: 'btn btn-primary btn-block' %>
  
<% end %>
<script type="text/javascript">
  $('#travel_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>
<div class="text-right">
  <%= link_to 'キャンセル', :back %>
</div>