config/routes.rb
Rails.application.routes.draw do

  get 'toppages', to: 'toppages#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  post 'guest', to: 'guest_sessions#create'

  resources :users, only: [:create]
  get 'signup', to: 'users#new'
  
  resources :travels, only: [:index, :new, :create, :destroy]
  root to: 'toppages#index'
  
  resources :budget_items, only: [:destroy, :update, :edit]
  get 'travels/:id/budget_items', to: 'budget_items#index',as: 'budget_items'
  get 'travels/:id/budget_items/new', to: 'budget_items#new',as: 'new_budget_item'
  post 'travels/:id/budget_items', to: 'budget_items#create'
  
  resources :paid_items, only: [:destroy, :update, :edit]
  get 'travels/:id/paid_items', to: 'paid_items#index',as: 'paid_items'
  get 'travels/:id/paid_items/new', to: 'paid_items#new',as: 'new_paid_item'
  post 'travels/:id/paid_items', to: 'paid_items#create'
  
end

app/models/paid_item.rb
class PaidItem < ApplicationRecord
  
  belongs_to :travel
  
  validates :name, presence: true, length: { maximum: 20 }
  validates :cost, presence: true, length: { maximum: 20 }, numericality: { only_integer: true }
  
end

app/controllers/paid_items_controller.rb
class PaidItemsController < ApplicationController
  
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :correct_user2, only: [:index, :new]
  before_action :set_paid_item, only: [:edit, :update, :destroy]
  before_action :set_travel, only: [:index, :new, :create]
  
  def index
    @paid_items = @travel.paid_items
  end

  def new
    @paid_item = PaidItem.new
  end

  def create
    @paid_item = @travel.paid_items.build(paid_item_params)
    
    if @paid_item.save
      flash[:success] = '項目を追加しました。'
      redirect_to paid_items_path
    else
      flash.now[:danger] = '項目の追加に失敗しました。'
      render :new
    end
  end

  def edit
    @travel = @paid_item.travel
  end
  
  def update
    @travel = @paid_item.travel
    
    if @paid_item.update(paid_item_params)
      flash[:success] = '項目を更新しました。'
      redirect_to paid_items_path(@paid_item.travel)
    else
      flash.now[:danger] = '項目の更新に失敗しました。'
      render :edit
    end
  end
  
  def destroy
    @paid_item.destroy
    flash[:success] = '項目を削除しました。'
    redirect_back(fallback_location: paid_items_path)
  end
  
  private
  
  def paid_item_params
    params.require(:paid_item).permit(:name, :cost)
  end
    
  def set_paid_item
    @paid_item = PaidItem.find(params[:id])
  end
  
  def set_travel
    @travel = Travel.find(params[:id])
  end
  
  def correct_user
    @paid_item = PaidItem.find(params[:id])
    unless @paid_item.travel.user == @current_user
      redirect_to travels_path
    end
  end
  
  def correct_user2
    @travel = Travel.find(params[:id])
    unless @travel.user == @current_user
      redirect_to travels_path
    end
  end
end
  

app/helpers/paid_items_helper.rb
module PaidItemsHelper
end

app/views/paid_items/_form.html.erb
<%= form_with(model: item, local: true) do |f| %>

<%= render 'layouts/error_messages', model: f.object %>

 <div class="form-group">
    <%= f.label :name, '項目名' %>
    <%= f.text_field :name, class: 'form-control' %>
 </div>
 <div class="form-group">
    <%= f.label :cost, '金額' %>
    <%= f.text_field :cost, class: 'form-control' %>
 </div>
  <%= f.submit '完了', class: 'btn btn-primary btn-block' %>
<% end %>
<div class="text-right">
  <%= link_to '戻る', :back %>
</div>

app/views/paid_items/edit.html.erb
<div class= 'text-center'>
  <h2><%= @travel.name %>　 項目編集(実績)</h2>
</div>

<%= render 'form', item: @paid_item %>

app/views/paid_items/index.html.erb
<div class= 'text-center'>
  <h2><%= @travel.name %>　実績</h2>
</div>
<div class= 'text-right'>
  <h2>合計<%= @paid_items.all.sum(:cost) %>円</h2>
  <%= link_to '項目追加',  new_paid_item_path %>　　<%= link_to '戻る', travels_path %>
</div>

<% @paid_items.each do |paid_item| %>
  <ul>
    <li><%= paid_item.name %> <%= paid_item.cost %>円　<%= link_to '編集', edit_paid_item_path(paid_item)  %>　<%= link_to '削除', paid_item, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %></li>
  </ul>
<% end %>

app/views/paid_items/new.html.erb
<div class= 'text-center'>
  <h2><%= @travel.name %> 　項目追加(実績)</h2>
</div>

<%= render 'form', item: @paid_item %>